config/routes.rb
TccJsapiDemo::Application.routes.draw do
  resources :customers

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :city, :name, :order_quantity, :profit, :profit_ratio, :sales, :state
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :sales %><br />
    <%= f.text_field :sales %>
  </div>
  <div class="field">
    <%= f.label :profit %><br />
    <%= f.text_field :profit %>
  </div>
  <div class="field">
    <%= f.label :order_quantity %><br />
    <%= f.text_field :order_quantity %>
  </div>
  <div class="field">
    <%= f.label :profit_ratio %><br />
    <%= f.text_field :profit_ratio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Customers to Look Into</h1>

<table class='display' id='customer-table'>
    <thead>
      <tr>
        <th>Name</th>
        <th>City</th>
        <th>State</th>
        <th>Sales</th>
        <th>Profit</th>
        <th>Order quantity</th>
        <th>Profit ratio</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.name %></td>
            <td><%= customer.city %></td>
            <td><%= customer.state %></td>
            <td><%= customer.sales %></td>
            <td><%= customer.profit %></td>
            <td><%= customer.order_quantity %></td>
            <td><%= customer.profit_ratio %></td>
            <td><%= link_to 'Show', customer %></td>
            <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
            <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
    <% end %>
    </tbody>
</table>

<script>
  $(document).ready(function() {
    $('#customer-table').dataTable();
  } );

</script>

<br />

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @customer.name %>
</p>

<p>
  <b>City:</b>
  <%= @customer.city %>
</p>

<p>
  <b>State:</b>
  <%= @customer.state %>
</p>

<p>
  <b>Sales:</b>
  <%= @customer.sales %>
</p>

<p>
  <b>Profit:</b>
  <%= @customer.profit %>
</p>

<p>
  <b>Order quantity:</b>
  <%= @customer.order_quantity %>
</p>

<p>
  <b>Profit ratio:</b>
  <%= @customer.profit_ratio %>
</p>


<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TccJsapiDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>